language: python
dist: xenial
python:
- '3.7'
install: pip install -e .
script: python -m unittest gayson/tests.py
deploy:
  provider: pypi
  user: serioeseGmbH
  on:
    branch: master
  password:
    secure: FSwoQR75L2e1IHQ59L8kiJVEqsB+vNUpmLoDszEtrOVdNzqnnYSmAfBGx+f14B7W/5EFIfjR3dO4Ac+8HBuT7dD52PgMabXOLF4jvhVgbb8eFE0MIM9GdzF+ztMLk9vo+iCNYsH88V2+FbqqDOh/hq5CmNTFKUgxrv7evpzT5P/+5gKI3rJ0uS1PGuQoANaiUjp7QiBPBYSYjTkGLYlFKMkPpM6rwSe77K1NKOndXEMd98+HOj0uFU9Y9MBG6ICoATex27+mjXSW+TIZ4xrNi0bCv3/0yZKgy6/veX2tHDfFS+kXWDiJjy90uZWqwZ9a4H/uaSxPA3t2r559fXUnsoOV8zmpiTK7QOnoejxy0lZ8VBceme+e7/vvVZTvyhaNqWOoZOllwpGjPxvFby/jZV1L6r2R+5bzGHxH5k3QHgzQR164Y/8XXhCANOJree1Dbl2ncOrckGizHR1W6JXO40WhrYj+xz7vRPwzQeqSCDLalrapw0TKe/2mIxNew2M+Btc5WW/n+qeO+smUOzRfrsMtkCv5//+ytBvbxl/7MN2N49c0g4dzSOzyMIHdGhgbrcLvYnzrTBeFkIJApAmeNYFR6jUUfoQMTErtXTwi+5YPm9dowxVCeG9bylesWh44Oxi2vAF924iSikjls31YxOaJx/WTCrfVMcMQfpIEV/4=
